"use client";
import "@/css/jupiter.scss";
export default function Jupiter() {


    return (
        <div className="scene">
  <div className="scene_titanShadow" />
  <div className="t_wrap">
    <div className="scene_titan">
      <div className="eyes">
        <div className="eye eye--left" />
        <div className="eye eye--right" />
      </div>
    </div>
  </div>
  <div className="scene_saturn">
    <div className="scene_saturn__face">
      <div className="face_clip">
        <div className="eye eye--left" />
        <div className="eye eye--right" />
        <div className="mouth" />
      </div>
    </div>
    <div className="scene_saturn__shadow" />
    <div className="scene_saturn__shadowRing" />
    <div className="scene_saturn__sparks">
      <div className="spark" />
      <div className="spark" />
      <div className="spark" />
      <div className="spark" />
      <div className="spark" />
      <div className="spark" />
      <div className="spark" />
      <div className="spark" />
      <div className="spark" />
      <div className="spark" />
      <div className="spark" />
      <div className="spark" />
      <div className="spark" />
      <div className="spark" />
      <div className="spark" />
      <div className="spark" />
      <div className="spark" />
      <div className="spark" />
      <div className="spark" />
      <div className="spark" />
    </div>
    <div className="scene_saturn__ring">
      <div className="small">
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
        <div className="small_part" />
      </div>
      <div className="layer">
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
      </div>
      <div className="layer">
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
      </div>
      <div className="layer">
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
        <div className="layer_part" />
      </div>
    </div>
  </div>
</div>
    );
}   